version: '3.8'

services:
  ltp:
    container_name: ltp
    env_file:
      - configs/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    working_dir: /usr/src/app
    restart: unless-stopped